### ISSUE TITLE
Running FED breaks tvcon display

### ISSUE THREAD

**Issue by larsbrinkhoff** [aap/tv11#1]
In ITS:

    :FED
    INPUT: fonts; 13fg

tvclient: core dumped.

**Comment by larsbrinkhoff** [comment]
On some rare occasions, even the tv11 crashes.

**Comment by larsbrinkhoff** [comment]
TVWRIT also exhibits the same problem.  Or at least very similar symptoms.

**Comment by aap** [comment]
Does that happen still?

**Comment by larsbrinkhoff** [comment]
It doesn't crash any more, but FED doesn't work.  The display goes all black and no longer updates, even though keyboard input is still accepted.  If I close the connection and start another one, the display has the expected contents including echoed characters I typed.

**Comment by larsbrinkhoff** [comment]
I still had this problem when I ran TVWRIT a few weeks ago.

**Comment by aap** [comment]
Should be fixed now. Was updating the screen with addresses that aren't visible which caused memory corruption in tvcon.
