### ISSUE TITLE
Gamma vs. nabla?

### ISSUE THREAD

**Issue by ams** [aap/tv11#23]
https://github.com/aap/tv11/blob/1bea0c7eeb9dedd0644dc60a10eadfeb94fbe83d/tvcon/tvcon.c#L260-L262

Shouldn't "O+ gamma" be "O+ nabla"?

**Comment by aap** [comment]
From TV 132:

    KBDKEY  42,     -4,     -6,     -4,     -6,             -6      ;plus-minus, delta
    KBDKEY  43,     -5,     -7,     -5,     -7,             -7      ;circle-plus, gamma

**Comment by ams** [comment]
Is @larsbrinkhoff wrong? That would be terrible ...

**Comment by ams** [comment]
TV 147 says the same, FWIW.

**Comment by larsbrinkhoff** [comment]
"Plus-minus, delta" and "circle-plus, gamma" are the keytop symbols.  Out of those, only ⊕ is a character in the SAIL set.

I don't know where I found that now, but at some point I figured the codes sent for ⊖, Δ, and ∇ were the SAIL characters ±, δ, and γ.

**Comment by larsbrinkhoff** [comment]
See the NASCTB table in TV11 software.

**Comment by ams** [comment]
I'm closing this, I think the answer is unclear enough that I can do that.  Keycaps aren't what we type.
