### ISSUE TITLE
Symbolic keyboard mapping

### ISSUE THREAD

**Issue by larsbrinkhoff** [aap/tv11#3]
Now that I have tested SUDS, I see the appeal of having a physical key mapping.  However, in most other cases I find this mapping barely usable.  I like to touch type with the now-standard US layout.

This is a request for comments, or really a discussion how to best solve this problem.

**Comment by larsbrinkhoff** [comment]
Note that DECUUO also has the option to map keys to the Stanford layout, or leave them as is.

**Comment by larsbrinkhoff** [comment]
Yes, I had this kind of solution in mind.  The TV client could check the logical symbol typed, and send whatever scan codes the TV-11 expects.

There should probably be a run time switch between logical and pysical mapping.

**Comment by larsbrinkhoff** [comment]
![knight-keyboard](https://user-images.githubusercontent.com/775050/43395750-7bb92c9e-93ff-11e8-84f2-f382fc0a5ee7.png)

**Comment by larsbrinkhoff** [comment]
I propose this key mapping as an option amongst others.

| US keyboard | Knight keyboard | Comment
| --- | --- | ---
| *unshifted* <kbd>A</kbd>-<kbd>A</kbd> | <kbd>A</kbd>-<kbd>Ƶ</kbd>
| <kbd>Shift</kbd> + <kbd>A</kbd>-<kbd>Z</kbd> | <kbd>SHIFT</kbd> + <kbd>A</kbd>-<kbd>Ƶ</kbd>
| <kbd>0</kbd>-<kbd>9</kbd> | <kbd>0</kbd>-<kbd>9</kbd>
| <kbd>!</kbd>, <kbd>@</kbd>, <kbd>#</kbd>, ... | <kbd>SHIFT</kbd> + <kbd>1</kbd>, <kbd>2</kbd>, <kbd>3</kbd>, ...
| Et cetera... | you get the idea
| <kbd>;</kbd> | <kbd>;</kbd>
| <kbd>Shift</kbd> + <kbd>;</kbd> (i.e. <kbd>:</kbd>) | <kbd>:</kbd> | Mapping symbols, not key positions
| <kbd>Control</kbd> | <kbd>CTRL</kbd>
| <kbd>Caps Lock</kbd> | <kbd>CTRL</kbd> | **!!!**
| <kbd>Alt</kbd> | <kbd>META</kbd>
| <kbd>Windows</kbd> | <kbd>TOP</kbd>
| <kbd>Esc</kbd> | <kbd>ALT</kbd>
| <kbd>Backspace</kbd> | <kbd>RUB OUT</kbd> | Note: both these
| <kbd>Delete</kbd> | <kbd>RUB OUT</kbd> | ...mapped to rubout
| <kbd>F1</kbd> | <kbd>CALL</kbd> | Arguably the most important special key
| <kbd>F2</kbd> | <kbd>ESC</kbd>
| <kbd>F3</kbd> | <kbd>BS</kbd> | <kbd>Backspace</kbd> as <kbd>BS</kbd> is not very useful
| *more F keys as needed* | <kbd>CLEAR</kbd>, <kbd>FORM</kbd>, <kbd>VT</kbd>, <kbd>LINE</kbd>, <kbd>BACK/NEXT</kbd>
| ? | <kbd>BREAK</kbd> | What does this even do?
| <kbd>Windows</kbd> + <kbd>A</kbd> | <kbd>TOP</kbd> + <kbd>A</kbd> (giving ≤)
| ... | | The obvious thing for <kbd>TOP</kbd> + letter
| <kbd>Windows</kbd> + <kbd>Z</kbd> | <kbd>TOP</kbd> + <kbd>Ƶ</kbd> (giving α)
| <kbd>Windows</kbd> + <kbd>/<kbd> | <kbd>TOP</kbd> + <kbd>/</kbd> (giving ∞)
| <kbd>F*n*</kbd> | <kbd>⊖</kbd>
| <kbd>F*n+1*</kbd> | <kbd>⊕</kbd>

**Comment by aap** [comment]
Can this be closed now?

**Comment by larsbrinkhoff** [comment]
Yes!
